language: generic

sudo: required
git:
  depth: false

services:
  - docker

env:
  global:
    - MIX_ENV=prod
    - DOCKER_IMAGE_NAME="btfontenot/mine:0.1.0"

jobs:
  include:
    - stage: "Tests"
      name: "Unit Tests"
      language: elixir
      elixir:
        - '1.10.3'
      otp_release:
        - '22.0'
      cache:
        directories:
          - deps
      install: 
        - mix local.hex --force
        - mix local.rebar --force
        - mix deps.get
        - nvm install 12.4.0 && nvm use 12.4.0
        - npm install --prefix assets
      script:
        MIX_ENV=test mix test
    
    - stage: docker
      name: 'deploy docker'
      if: branch = master
      before_install:
        # docker build -t btfontenot/mine:0.1.0 .
        docker-compose build
      script:
        - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
        - docker push DOCKER_IMAGE_NAME

    - stage: aws
      name: 'deploy aws'
      if: branch = master
      deploy:
        provider: elasticbeanstalk
        region: us-east-2
        app: mine_app
        env: MineApp-env
        bucket_name: elasticbeanstalk-us-east-2-560687854181
        bucket_path: mine_app
        on:
          branch: master
        access_key_id: $AWS_ACCESS_KEY
        secret_access_key: $AWS_SECRET_KEY