
# services:
#   - docker

# os:
#   -linux

# env:
#   global:
#     - DOCKER_IMAGE_NAME=""

# before_scripts:

# script:

# after_script:


# deploy:
#   provider: s3
#   access_key_id: "YOUR AWS ACCESS KEY"
#   secret_access_key: "YOUR AWS SECRET KEY"
#   bucket: "S3 Bucket"

############################


env:
  global:
    - MIX_ENV=prod

jobs:
  include:
    - stage: "Tests"
      name: "Unit Tests"
      language: elixir
      elixir:
        - '1.10.3'
      otp_release:
        - '22.0'
      cache:
        directories:
          - deps

      install: 
        - mix local.hex --force
        - mix local.rebar --force
        - mix deps.get
        - nvm install 12.4.0 && nvm use 12.4.0
        - npm install --prefix assets
      script:
        MIX_ENV=test mix test
