# syntax = docker/dockerfile:1.0-experimental
FROM elixir:1.10.0-alpine AS build

# install build dependencies
RUN apk add --no-cache build-base npm git python

# prepare build dir
WORKDIR /app

# install hex + rebar
RUN mix local.hex --force && \
    mix local.rebar --force

# set build ENV
ENV MIX_ENV=prod

# install mix dependencies
COPY mix.exs mix.lock ./
COPY config config
RUN mix do deps.get, deps.compile

# build assets
COPY assets/package.json assets/package-lock.json ./assets/
RUN npm --prefix ./assets ci --progress=false --no-audit --loglevel=error

COPY priv priv
COPY assets assets
RUN npm run --prefix ./assets deploy
RUN mix phx.digest

# compile and build release
COPY lib lib
# uncomment COPY if rel/ exists
# COPY rel rel
RUN --mount=type=secret,id=secret_keys export SECRET_KEY_BASE=$(sed -n 1p /run/secrets/secret_keys) && \
    export REDDIT_API_KEY=$(sed -n 2p /run/secrets/secret_keys) && \
    export REDDIT_CLIENT_ID=$(sed -n 3p /run/secrets/secret_keys) && \
    export REDDIT_REDIRECT_URI=$(sed -n 4p /run/secrets/secret_keys) && \
    mix do compile, release
# RUN mix do compile, release

# prepare release image
FROM alpine:3.9 AS app
RUN apk add --no-cache openssl ncurses-libs

WORKDIR /app

RUN chown nobody:nobody /app

USER nobody:nobody

COPY --from=build --chown=nobody:nobody /app/_build/prod/rel/mine ./

ENV HOME=/app

CMD ["bin/mine", "start"]