use Mix.Config

# For production, don't forget to configure the url host
# to something meaningful, Phoenix uses this information
# when generating URLs.
#
# Note we also include the path to a cache manifest
# containing the digested version of static files. This
# manifest is generated by the `mix phx.digest` task,
# which you should run after static files are built and
# before starting your production server.

config :mine, MineWeb.Endpoint,
  server: true,
  url: [host: "mineapp-env.eba-nxjz2ubz.us-east-2.elasticbeanstalk.com", port: 3000],
  cache_static_manifest: "priv/static/cache_manifest.json",
  http: [
    transport_options: [socket_opts: [:inet6]],
    port: 3000]

# Do not print debug messages in production
config :logger, level: :info

# Use JASON for parsing json data
config :phoenix, :json_library, Jason
