use Mix.Config

# For production, don't forget to configure the url host
# to something meaningful, Phoenix uses this information
# when generating URLs.
#
# Note we also include the path to a cache manifest
# containing the digested version of static files. This
# manifest is generated by the `mix phx.digest` task,
# which you should run after static files are built and
# before starting your production server.
secret_key_base =
  System.get_env("SECRET_KEY_BASE") ||
    raise """
    environment variable SECRET_KEY_BASE is missing.
    You can generate one by calling: mix phx.gen.secret
    """

config :mine, MineWeb.Endpoint,
  server: true,
  url: [host: "mineapp-env.eba-nxjz2ubz.us-east-2.elasticbeanstalk.com", port: 3000],
  # force_ssl: [rewrite_on: [:x_forwarded_proto]],
  cache_static_manifest: "priv/static/cache_manifest.json",
  secret_key_base: secret_key_base,
  http: [
    transport_options: [socket_opts: [:inet6]],
    port: 3000]

# Do not print debug messages in production
config :logger, level: :info

reddit_api_key =
  System.get_env("REDDIT_API_KEY") ||
    raise """
    environment variable REDDIT_API_KEY is missing.
    """

reddit_client_id =
  System.get_env("REDDIT_CLIENT_ID") ||
    raise """
    environment variable REDDIT_API_KEY is missing.
    """

reddit_redirect_uri =
  System.get_env("REDDIT_REDIRECT_URI") ||
    raise """
    environment variable REDDIT_REDIRECT_URI is missing.
    """

config :mine, reddit_api_key: reddit_api_key
config :mine, reddit_client_id: reddit_client_id
config :mine, reddit_redirect_uri: reddit_redirect_uri
